- exp018&rule001

In [1]:
import pandas as pd
from pathlib import Path

class CFG:
    name = "ens002"
    seed = 42

    path_input = Path("../input")
    path_output = Path("../output")

In [2]:
def setup(CFG):
    # expフォルダを作成
    CFG.path_exp = CFG.path_output / CFG.name
    CFG.path_exp.mkdir(parents=True, exist_ok=True)

    return CFG

CFG = setup(CFG)

In [3]:
sub1 = pd.read_csv("../output/rule001/submission.csv")
sub2 = pd.read_csv("../output/exp018/submission.csv")

display(sub1.head())

sub1 = sub1.values
sub2 = sub2.values

,predict_0,predict_1,predict_2,predict_3,predict_4,predict_5,predict_6,predict_7,predict_8,predict_9
0,3560,4714,2680,4420,11561,5466,9830,2040,2305,2811
1,143,4066,6555,7014,7913,6129,8108,11237,12862,613
2,757,757,7710,9190,10485,410,1774,3400,6721,6730
3,12341,3359,12341,5080,6991,10746,13521,277,1542,2047
4,9020,2862,3476,3844,3854,4070,5372,5411,6161,6565

In [4]:
# sub1の各行で繰り返し
for i in range(sub1.shape[0]):
    # 対応する行を取得
    sub1_row = sub1[i]
    for j, pred in enumerate(sub1_row):
        # 予測値が0なら
        if pred == 0:
            for pred2 in sub2[i]:
                # sub1の予測値にないものを探す
                if pred2 not in set(sub1[i]):
                    sub1[i][j] = pred2

In [5]:
sub = pd.DataFrame(sub1, columns=["predict_0", "predict_1", "predict_2", "predict_3", "predict_4", "predict_5", "predict_6", "predict_7", "predict_8", "predict_9"])

In [6]:
sub

,predict_0,predict_1,predict_2,predict_3,predict_4,predict_5,predict_6,predict_7,predict_8,predict_9
0,3560,4714,2680,4420,11561,5466,9830,2040,2305,2811
1,143,4066,6555,7014,7913,6129,8108,11237,12862,613
2,757,757,7710,9190,10485,410,1774,3400,6721,6730
3,12341,3359,12341,5080,6991,10746,13521,277,1542,2047
4,9020,2862,3476,3844,3854,4070,5372,5411,6161,6565
...,...,...,...,...,...,...,...,...,...,...
174695,1997,1997,2278,5744,7062,7888,9543,9743,10997,11123
174696,12432,1227,3802,899,2164,3644,4014,13220,13702,448
174697,13241,844,2087,5810,7308,7379,8143,11796,12240,12939
174698,2692,3100,10287,2305,2373,2510,3002,3096,4976,5079
174699,10729,1891,11994,12767,634,867,3781,5623,7690,10298

In [7]:
sub.to_csv(CFG.path_exp / "submission.csv", index=False)